"git":
  "depth": !!bool >-
    false
"language": >-
  nix
"matrix":
  "include":
  - "before_cache":
    - >-
      echo "pushing these paths to cachix:"
    - >-
      cat $HOME/push-to-cachix
    - >-
      cachix push lorri-test < $HOME/push-to-cachix
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/liblorri.rlib"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/lorri*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/build/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/liblorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/.fingerprint/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/build_script_build-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/direnv-*"
    "cache":
      "directories":
      - >-
        $HOME/.cargo
      - >-
        $TRAVIS_BUILD_DIR/target
    "env":
    - >-
      CACHE_NAME=linux
    "install":
    - >-
      sudo mkdir -p /etc/nix
    - >-
      echo "build-users-group =" | sudo tee -a /etc/nix/nix.conf
    - >-
      nix-env -iA cachix -f https://cachix.org/api/v1/install
    - >-
      cachix use lorri-test
    "language": >-
      nix
    "name": >-
      cargo build & linters
    "nix": >-
      2.2.1
    "os": >-
      linux
    "script":
    - >-
      set -e
    - >
      export LC_ALL=C.UTF-8

      export LC_CTYPE=C.UTF-8

      export LANG=C.UTF-8

      export LANGUAGE=C.UTF-8
    - >-
      cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
    - >-
      git diff -q ./.travis.yml
    - >
      testsuite=$(nix-build --arg isDevelopmentShell false -A ci.testsuite shell.nix)

      eval "$testsuite"
    - >-
      printf '%s' "$testsuite" >> $HOME/push-to-cachix
  - "before_cache":
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/liblorri.rlib"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/lorri*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/build/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/liblorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/.fingerprint/lorri-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/build_script_build-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/deps/direnv-*"
    - >-
      rm -rvf "$TRAVIS_BUILD_DIR/target/debug/incremental/direnv-*"
    "cache":
      "directories":
      - >-
        $HOME/.cargo
      - >-
        $TRAVIS_BUILD_DIR/target
    "env":
    - >-
      CACHE_NAME=macos
    "install":
    - >-
      sudo mkdir -p /etc/nix
    - >-
      echo "build-users-group =" | sudo tee -a /etc/nix/nix.conf
    "language": >-
      nix
    "name": >-
      cargo build & linters
    "nix": >-
      2.0
    "os": >-
      osx
    "script":
    - >-
      set -e
    - >
      export LC_ALL=C.UTF-8

      export LC_CTYPE=C.UTF-8

      export LANG=C.UTF-8

      export LANGUAGE=C.UTF-8
    - >-
      cat $(nix-build --quiet ./.travis.yml.nix --no-out-link) > .travis.yml
    - >-
      git diff -q ./.travis.yml
    - >
      testsuite=$(nix-build --arg isDevelopmentShell false -A ci.testsuite shell.nix)

      eval "$testsuite"
    - >-
      printf '%s' "$testsuite" >> $HOME/push-to-cachix
  - "before_cache":
    - >-
      echo "pushing these paths to cachix:"
    - >-
      cat $HOME/push-to-cachix
    - >-
      cachix push lorri-test < $HOME/push-to-cachix
    "install":
    - >-
      sudo mkdir -p /etc/nix
    - >-
      echo "build-users-group =" | sudo tee -a /etc/nix/nix.conf
    - >-
      nix-env -iA cachix -f https://cachix.org/api/v1/install
    - >-
      cachix use lorri-test
    "language": >-
      nix
    "name": >-
      nix-build
    "nix": >-
      2.2.1
    "os": >-
      linux
    "script":
    - >-
      set -e
    - >-
      nix-build
    - >-
      nix-env -i ./result
    - >-
      lorri self-upgrade local $(pwd)
    - >-
      readlink ./result >> $HOME/push-to-cachix
  - "install":
    - >-
      sudo mkdir -p /etc/nix
    - >-
      echo "build-users-group =" | sudo tee -a /etc/nix/nix.conf
    "language": >-
      nix
    "name": >-
      nix-build
    "nix": >-
      2.0
    "os": >-
      osx
    "script":
    - >-
      set -e
    - >-
      nix-build
    - >-
      nix-env -i ./result
    - >-
      lorri self-upgrade local $(pwd)
    - >-
      readlink ./result >> $HOME/push-to-cachix
